### ISSUE TITLE
stop and start Condon for gene prediction is not reliable

### ISSUE THREAD

**Issue by jianshu93** [jiwoongbio/MetaPrism#4]
No gene prediction software were used for reliable prediction of genes. Using only start and stop Condon can make mistakes without using hidden malcof model. Please use prodigal or GeneMark.hmm for gene prediction and then do the mapping for abundance calculation. Uniref 100 is also available now and is very useful. Can you please update.

Thanks,

Jianshu

**Comment by jiwoongbio** [comment]
We tested the ORF translation mapping (I don't want to call it gene prediction, its goal is to maximize mapping of target genes) comparing to GeneMark and the gene annotations of NCBI genome assemblies and got better detections of target genes - it will be included in the manuscript.

**Comment by jianshu93** [comment]
Thanks for the response. In that case why do people do gene prediction? It is useful for finding genes with which their stop and start were not assembled or not available I think for fragmented contigs right? Can I have a look at the preprint? Thanks Jianshu

________________________________

**Comment by jiwoongbio** [comment]
Again, it is not a gene prediction, it does not identify all the genes the genome or metagenome has. Instead, it identifies the genes or proteins in the database, so it is something like supervised one. What we tested is gene prediction -> target mapping vs. all possible ORFs -> target mapping.

**Comment by jiwoongbio** [comment]
About the fragmented ones, are you sure that they are assembly issues, not real incomplete genes? Actually, we have another program to detect that kind of fragmented gene cases using split read method, but it is not included yet because the additionally found genes were not experimentally validated.

**Comment by jianshu93** [comment]
Thanks for the explanation. RPKM/FPKM I have for some gene is like 600, which means the number of reads mapped to this gene, divided by 1000, then divided by 1000,000 is 600, I am a little surprised, more than 1000,000x1000x600 reads were mapped to a single gene, considering that fact that I have total 350,000,000 reads in total.

**Comment by jianshu93** [comment]
I still prefer using gene prediction before reads mapping but not just translation especially for metagenomic dataset (multiple species). Would that be ok if I modified it a little bit: do gene prediction using prodigal (or MetaGeneMark, do not use GeneMark because it is not optimized for fragmented genome, I am one of the students of  Prof.Mark Borovozsky actually) and then do reads mapping and functional annotation based on the predicted genes (can be nt in fasta format)

Thanks,

Jianshu

**Comment by jiwoongbio** [comment]
Thanks for your interest in MetaPrism, but I think you'd better make your own program for your specific case.
